# Generated by Django 3.2.10 on 2022-08-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=51)),
                ('description', models.CharField(max_length=201)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
